version: '3.8'

services:
  backend:
    build:
      context: ./api
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8200:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=test_fastapi_vuejs
    volumes:
      - ./api/app:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile    
    ports:
      - "8300:3000"
    command: "npm run dev"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8100:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #     - frontend

  db:
    image: bitnami/mariadb:latest
    restart: unless-stopped
    environment:
      # MYSQL_USER: lukyss
      # MYSQL_PASSWORD: root
      # MYSQL_DATABASE: cyka
      # MYSQL_ROOT_PASSWORD: rootpassword
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - "./init_db/:/docker-entrypoint-initdb.d/"
