version: '3.8'

services:
  backend:
    build:
      context: ./api
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8200:8000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=test_fastapi_vuejs
    volumes:
      - ./api/app:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile    
    ports:
      - "8300:3000"
    command: "npm run dev"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "8100:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #     - frontend

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_fastapi_vuejs
